## use ws2812-spi
CONFIG_SPI=y
#CONFIG_WS2812_STRIP=y
CONFIG_LED_STRIP=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_WS2812=y
CONFIG_RGBLED_WIDGET_LED_COUNT=2

CONFIG_RGBLED_WIDGET_BRIGHTNESS=64
# Turn off the WS2812 power rail 1 second after the indicators become idle.
CONFIG_RGBLED_WIDGET_EXT_POWER_TIMEOUT_MS=1000

CONFIG_RGBLED_WIDGET_LED_SHARING=y
