name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "boards/**"
      - "config/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
